version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        - BACKEND_CONTAINER_NAME=localhost
    ports:
      - "3000:3000"
    restart: always

  backend:
    container_name: backend  # Explicitly setting the container name as "backend"
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    restart: always
    network_mode: "host"
